server/buses/urls.py
from django.urls import path
from . import views

app_name = 'buses'

urlpatterns = [

    path('buses', views.BusSearchView.as_view(), name = 'Search'),
    path('buses/list', views.BusDisplayView.as_view(), name = 'Display'),
    path('buses/view/<slug:id>', views.BusDetailsView.as_view(), name = 'Details'),
    path('buses/bookings/<slug:id>', views.BusBookingListView.as_view(), name = 'Bookings'),


]

server/hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [

    path('hotels', views.HotelSearchView.as_view(), name = 'Search'),
    path('hotels/list', views.HotelDisplayView.as_view(), name = 'Display'),
    path('hotels/view/<slug:id>', views.HotelDetailsView.as_view(), name = 'Details'),
    path('hotels/bookings/<slug:id>', views.HotelBookingListView.as_view(), name = 'Bookings'),

]

server/server/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [

    path('upcoming', views.UpcomingView.as_view(), name = 'Upcoming'),
    path('past', views.PastView.as_view(), name = 'Past'),
    path('view/<slug:id>', views.BookingDetailView.as_view(), name = 'Detail'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('person.urls')),
    path('', include('hotels.urls')),
    path('', include('buses.urls')),
    path('booking/', include('booking.urls'))
]

server/server/booking/models.py
from django.db import models

# Create your models here.

server/server/booking/forms.py
from django import forms
from database import utils, models
from django.utils.crypto import get_random_string

class DeleteBookingForm(forms.Form):
    password = forms.CharField(required = True, max_length = 100)

server/server/booking/views.py
from django.shortcuts import render, redirect, reverse
from urllib.parse import quote, unquote
from django.views import View
from database import utils, models
from accounts.authentication import is_authenticated, get_type
from django.contrib.auth.hashers import make_password, check_password
from . import forms
import datetime

class UpcomingView(View):

    template_name = 'booking/upcoming_hotels.html'
    template_name_1 = 'booking/upcoming_buses.html'

    def get(self, request):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            if request.GET.get('type') != 'buses':
                hotel_bookings = utils.get_hotel_booking_by_user(request.session.get('email'))
                upcoming_bookings = []
                for booking in hotel_bookings:
                    date = datetime.datetime.strptime(booking.get('out_date'), "%Y-%m-%d").date()
                    if date < datetime.date.today():
                        continue
                    else:
                        hotel_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': hotel_detail.name})
                        upcoming_bookings.append(booking)
                return render(request, self.template_name, {'hotel_bookings': upcoming_bookings, 'type': get_type(request)})
            else:
                bus_bookings = utils.get_bus_booking_by_user(request.session.get('email'))
                upcoming_bookings = []
                for booking in bus_bookings:
                    date = datetime.datetime.strptime(booking.get('To'), "%Y-%m-%d").date()
                    if date < datetime.date.today():
                        continue
                    else:
                        bus_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': bus_detail.name})
                        upcoming_bookings.append(booking)
                return render(request, self.template_name, {'bus_bookings': upcoming_bookings, 'type': get_type(request)})
            

class PastView(View):

    template_name = 'booking/past_hotels.html'
    template_name_1 = 'booking/past_buses.html'

    def get(self, request):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            if request.GET.get('type') != 'buses':
                hotel_bookings = utils.get_hotel_booking_by_user(request.session.get('email'))
                past_bookings = []
                for booking in hotel_bookings:
                    date = datetime.datetime.strptime(booking.get(out_date), "%Y-%m-%d").date()
                    if date >= datetime.date.today():
                        continue
                    else:
                        hotel_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': hotel_detail.name})
                        past_bookings.append(booking)
                return render(request, self.template_name, {'hotel_bookings': past_bookings, 'type': get_type(request)})
            else:
                bus_bookings = utils.get_bus_booking_by_user(request.session.get('email'))
                past_bookings = []
                for booking in bus_bookings:
                    date = datetime.datetime.strptime(booking.get('To'), "%Y-%m-%d").date()
                    if date >= datetime.date.today():
                        continue
                    else:
                        bus_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': bus_detail.name})
                        past_bookings.append(booking)
                return render(request, self.template_name_1, {'bus_bookings': past_bookings, 'type': get_type(request)})
                


class BookingDetailView(View):

    template_name = 'booking/details_hotel.html'
    template_name_1 = 'booking/details_bus.html'

    def get(self, request, id):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            form = forms.DeleteBookingForm()
            if id[0] == 'H':
                booking_details = models.BookingMetaData.objects.filter(id=id)
                if not booking_details:
                    print('NOT FOUND')
                else:
                    booking = utils.get_hotel_booking_by_id(id)
                    if booking.get('email') != request.session.get('email'):
                        print('NOT FOUND')
                    else:
                        hotel = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        return render(request, self.template_name, {'form': form, 'booking': booking, 'hotel': hotel, 'type': get_type(request)})
            
            if id[0] == 'B':
                booking_details = models.BookingMetaData.objects.filter(id=id)
                if not booking_details:
                    print('NOT FOUND')
                else:
                    booking = utils.get_bus_booking_by_id(id)
                    if booking.get('email') != request.session.get('email'):
                        print('NOT FOUND')
                    else:
                        bus = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        return render(request, self.template_name_1, {'form': form, 'booking': booking, 'bus': bus, 'type': get_type(request)})                        

    def post(self, request, id):
        userInfo = models.UserMetaData.objects.get(email = request.session.get('email'))
        db_name = userInfo.db_name
        if id[0] == 'H':
            booking = utils.get_hotel_booking_by_id(id)
            hotel = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
            form = forms.DeleteBookingForm(request.POST)
            if form.is_valid():
                user = utils.get_user(db_name, request.session.get('email'))
                if check_password(form.cleaned_data.get('password'), user.get('password')) == True:
                    r = utils.delete_hotel_booking(id)
                    if r == 200:
                        return redirect('person:Dashboard')
                    else:
                        return render(request, self.template_name, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Network Error', 'booking': booking, 'hotel': hotel, 'type': get_type(request)})
                else:
                    return render(request, self.template_name, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Incorrect Password', 'booking': booking, 'hotel': hotel, 'type': get_type(request)})
            else:
                return render(request, self.template_name, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Fields cannot be empty', 'booking': booking, 'hotel': hotel, 'type': get_type(request)})

        if id[0] == 'B':
            booking = utils.get_bus_booking_by_id(id)
            hotel = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
            form = forms.DeleteBookingForm(request.POST)
            if form.is_valid():
                user = utils.get_user(db_name, request.session.get('email'))
                if check_password(form.cleaned_data.get('password'), user.get('password')) == True:
                    r = utils.delete_bus_booking(id)
                    if r == 200:
                        return redirect('person:Dashboard')
                    else:
                        return render(request, self.template_name_1, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Network Error', 'booking': booking, 'bus': bus, 'type': get_type(request)})
                else:
                    return render(request, self.template_name_1, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Incorrect Password', 'booking': booking, 'bus': bus, 'type': get_type(request)})
            else:
                return render(request, self.template_name_1, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Fields cannot be empty', 'booking': booking, 'bus': bus, 'type': get_type(request)})

        

server/booking/templates/booking/details_bus.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Bus Details{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <div class="columns">
            <div class="column is-2">
                <a class="button" onclick="goBack()"><< &nbsp; BACK</a>
            </div>
            <div class="column is-8">
                <div class="subtitle is-3">
                    Booking Details
                </div>
                <div class="has-text-left section">

                    <div class="box">
                        <form>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Booking ID</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="input is-medium is-disabled is-rounded">
                                            {{ booking.id }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Bus</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="input is-medium is-disabled is-rounded">
                                            {{ bus.name }}
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-medium is-link is-outlined" href="{% url 'buses:Details' id=bus.id %}">
                                            Visit
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Dates</label>
                                </div>
                                <div class="field-body box">
                                    <div class="field">
                                        <div>
                                            From: &nbsp; <span class="tag is-medium is-rounded">{{ booking.From }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div>
                                            To: &nbsp; <span class="tag is-medium is-rounded">{{ booking.To }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Booking Date</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="input is-medium is-disabled is-rounded">
                                            {{ booking.booking_date }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Seats</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="tag is-large is-primary is-rounded">
                                            {{ booking.seats }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Amount</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="input is-medium is-disabled is-rounded">
                                            INR &nbsp; {{ booking.bill }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label">Status</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="input is-medium is-disabled is-rounded">
                                            <span style="color: green;">Payment Successful.</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="section has-text-centered">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">Cancel Booking</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div>
                                        {% render_field form.password type="password" class="input is-rounded" placeholder="Your Password" %}
                                    </div>
                                </div>
                                <div class="field">
                                    <button class="button is-danger is-outlined is-rounded is-fullwidth">
                                        Confirm
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                    <!-- MESSAGES -->
                    <div>
                        {% if error %}
                        <div class="content">
                            <span style="color: red;">{{ msg }}</span>
                        </div>
                        {% endif %}
                    </div>
                    <!-- MESSAGES END -->

                </div>

            </div>
            <div class="column is-2">
                <a class="button">Print Booking</a>
            </div>
        </div>

    </div>

    <script>
        function goBack(){
            window.history.back();
        }
    </script>

{% endblock %}

server/booking/templates/booking/past_bus.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Upcoming Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">PAST TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Past' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Past' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}">Upcoming Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Bus Bookings</div>

                    {% if bus_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for bus in bus_bookings %}
                        <form class="box">
                            <div class="field is-horizontal">

                                <div class="field-body">
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <a href="{% url 'bus:Details' id=bus.service_id %}">{{ bus.service_name }}</a>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ bus.seats }} seats</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ bus.From }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ bus.To }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-rounded" href="{% url 'booking:Detail' id=bus.id %}">
                                            Booking Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}

server/booking/templates/booking/past_hotels.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Upcoming Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">PAST TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Past' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Past' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}">Upcoming Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Hotel Bookings</div>

                    {% if hotel_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for hotel in hotel_bookings %}
                        <form class="box">
                            <div class="field is-horizontal">

                                <div class="field-body">
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <a href="{% url 'hotels:Details' id=hotel.service_id %}">{{ hotel.service_name }}</a>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ hotel.rooms }} rooms</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ hotel.in_date }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ hotel.out_date }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-rounded" href="{% url 'booking:Detail' id=hotel.id %}">
                                            Booking Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}

server/booking/templates/booking/upcoming_buses.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Upcoming Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">UPCOMING TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Upcoming' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Past' %}">Past Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Bus Bookings</div>

                    {% if bus_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for bus in bus_bookings %}
                        <form class="box">
                            <div class="field is-horizontal">

                                <div class="field-body">
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <a href="{% url 'buses:Details' id=bus.service_id %}">{{ bus.service_name }}</a>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ bus.seats }} seats</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ bus.From }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ bus.To }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-rounded" href="{% url 'booking:Detail' id=bus.id %}">
                                            Booking Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}