server/buses/urls.py
from django.urls import path
from . import views

app_name = 'buses'

urlpatterns = [

    path('buses', views.BusSearchView.as_view(), name = 'Search'),
    path('buses/list', views.BusDisplayView.as_view(), name = 'Display'),
    path('buses/view/<slug:id>', views.BusDetailsView.as_view(), name = 'Details'),
    path('buses/bookings/<slug:id>', views.BusBookingListView.as_view(), name = 'Bookings'),


]

server/hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [

    path('hotels', views.HotelSearchView.as_view(), name = 'Search'),
    path('hotels/list', views.HotelDisplayView.as_view(), name = 'Display'),
    path('hotels/view/<slug:id>', views.HotelDetailsView.as_view(), name = 'Details'),
    path('hotels/bookings/<slug:id>', views.HotelBookingListView.as_view(), name = 'Bookings'),

]

server/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [

    path('dashboard', views.DashboardView.as_view(), name = 'Dashboard'),
    path('manage', views.AdminView.as_view(), name = 'Admin'),
    path('logout', views.LogoutView.as_view(), name = 'Logout'),
    path('services', views.ServiceView.as_view(), name = 'Services'),
    path('service/<slug:id>', views.EditServiceView.as_view(), name = 'EditService'),
    path('delete_manager_from_service/<slug:id>/<slug:email>', views.DeleteManagerView.as_view(), name = 'DeleteManager'),
    path('delete_bus_route/<slug:id>/<int:index>', views.DeleteRouteView.as_view(), name = 'DeleteBusRoute'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('person.urls')),
    path('', include('hotels.urls')),
    path('', include('buses.urls')),
    path('booking/', include('booking.urls'))
]

server/person/forms.py
from django import forms
from database import utils, models
from django.utils.crypto import get_random_string

class UserPrivilageForm(forms.Form):
    CHOICES = ( ('U', 'Standard User'),
                ('A', 'Admin'),
                ('S', 'Service Provider'),)
    email = forms.EmailField(max_length = 100, required = True)
    privilage = forms.ChoiceField(choices = CHOICES, widget = forms.Select)

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def clean_privilage(self):
        privilage = self.cleaned_data['privilage']
        email = self.cleaned_data['email']
        user = self.get_object(email)
        if user.count() > 0:
            user = user[0]
            r = utils.update_user(user.db_name, user.email, type = privilage)
            if r == 200:
                return privilage
            else:
                raise forms.ValidationError('Network Error')
        else:
            raise forms.ValidationError('User not found')

class PasswordForm(forms.Form):
    password = forms.CharField(required = True, max_length = 100)

class ManagersForm(forms.Form):
    email = forms.EmailField(max_length = 100, required = True)

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = self.get_object(email)
        if user.count() > 0:
            user = user[0]
            user = utils.get_user(user.db_name, user.email)
            if user.get('type') == 'S':
                return email
            else:
                raise forms.ValidationError('User not a service provider')
        else:
            raise forms.ValidationError('User does not exist')


class NewServiceForm(forms.Form):
    CHOICES = ( ('B', 'Bus Service'),
                ('H', 'Hotel Service'),)
    name = forms.CharField(max_length = 100, required = True)
    service_type = forms.ChoiceField(choices = CHOICES, widget = forms.Select)

class EditBusServiceForm(forms.Form):
    CHOICES = ( ('B', 'Bus Service'),
                ('H', 'Hotel Service'),)
    id = forms.CharField(max_length = 100, required = True, widget = forms.TextInput(attrs={'readonly': True}))
    name = forms.CharField(max_length = 100, required = True)
    service_type = forms.CharField(widget = forms.TextInput(attrs={'readonly': True}))
    bus_number = forms.CharField(max_length = 20, required = True)
    seats = forms.IntegerField(required = True)
    price = forms.IntegerField(required = True)
    is_ready = forms.BooleanField(required = False)

class EditRouteForm(forms.Form):
    stop_name = forms.CharField(max_length = 100, required = True)
    day = forms.IntegerField(min_value = 0, required = True)
    time_hour = forms.IntegerField(min_value = 0, max_value = 23, required = True)
    time_mins = forms.IntegerField(min_value = 0, max_value = 59, required = True)
    boarding_point = forms.CharField(max_length = 100, required = True)

class EditHotelServiceForm(forms.Form):
    CHOICES = ( ('B', 'Bus Service'),
                ('H', 'Hotel Service'),)
    id = forms.CharField(max_length = 100, required = True, widget = forms.TextInput(attrs={'readonly': True}))
    name = forms.CharField(max_length = 100, required = True)
    service_type = forms.CharField(widget = forms.TextInput(attrs={'readonly': True}))
    city = forms.CharField(max_length = 100, required = True)
    area = forms.CharField(max_length = 100, required = True)
    address = forms.CharField(max_length = 200, required = True)
    description = forms.CharField(required = True, widget = forms.Textarea)
    rooms = forms.IntegerField(required = True)
    price = forms.IntegerField(required = True)
    is_ready = forms.BooleanField(required = False)
    check_in = forms.TimeField(required = True)
    check_out = forms.TimeField(required = True)

server/person/views.py
from django.shortcuts import render, redirect
from django.views import View
from database import utils, models
from accounts.authentication import is_authenticated, get_type
from django.contrib.auth.hashers import make_password, check_password
from . import forms
from django.utils.crypto import get_random_string

class DashboardView(View):
    template_name = 'person/dashboard.html'

    def get(self, request):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            return render(request, self.template_name, {'type': get_type(request)})

class AdminView(View):
    template_name = 'person/admin.html'

    def check_status(self):
        return utils.check_status()

    def get(self, request):
        if is_authenticated(request) != None and get_type(request) == 'A':
            form1 = forms.UserPrivilageForm()
            dbs = models.DatabaseDetails.objects.order_by('name')
            return render(request, self.template_name, {'form1': form1, 'dbs': dbs, 'type': get_type(request)})
        else:
            return redirect('accounts:Login')

    def post(self, request):
        form1 = forms.UserPrivilageForm()
        if 'user_privilage' in request.POST:
            form1 = forms.UserPrivilageForm(request.POST)
            if form1.is_valid():
                return render(request, self.template_name, {'form1': forms.UserPrivilageForm(), 'type': get_type(request), 'success1': '1', 'msg1': 'Request Processed'})
            else:
                return render(request, self.template_name, {'form1': form1, 'type': get_type(request), 'error1': '1'})
        elif 'database_edit' in request.POST:
            db = models.DatabaseDetails.objects.filter(name = request.POST.get('name'))[0]
            db.ip_addr = request.POST.get('ip_addr')
            db.port = request.POST.get('port')
            db.save()
            utils.update_database_status()
            return redirect('person:Admin')

class ServiceView(View):
    template_name = 'person/services.html'

    def get_object(self, email):
        return models.ServiceMetaData.objects.filter(provider__contains=list([email]))

    def get(self, request):
        if is_authenticated(request) != None:
            if get_type(request) == 'S':
                services = utils.get_bus_service_by_email(request.session.get('email'))
                services1 = utils.get_hotel_service_by_email(request.session.get('email'))
                form = forms.NewServiceForm()
                return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request)})
            else:
                return redirect('person:Dashboard')
        else:
            return redirect('accounts:Login')

    def post(self, request):
        services = utils.get_bus_service_by_email(request.session.get('email'))
        services1 = utils.get_hotel_service_by_email(request.session.get('email'))
        if 'new_service' in request.POST and request.POST.get('service_type') == 'B':
            form = forms.NewServiceForm(request.POST)
            if form.is_valid():
                service_type = form.cleaned_data.get('service_type')
                id = 'B' + get_random_string(15)
                while utils.check_service_id(id) == False:
                    id = 'B' + get_random_string(15)
                db_name = utils.get_database_name()
                provider = request.session.get('email')
                r = utils.insert_bus_service(db_name, id, form.cleaned_data.get('name'), provider)
                if r == 201:
                    return redirect('person:EditService', id = id)
                else:
                    return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Network Error'})
            else:
                return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Invalid Details'})
        elif 'new_service' in request.POST and request.POST.get('service_type') == 'H':
            form = forms.NewServiceForm(request.POST)
            if form.is_valid():
                service_type = form.cleaned_data.get('service_type')
                id = 'H' + get_random_string(15)
                while utils.check_service_id(id) == False:
                    id = 'H' + get_random_string(15)
                db_name = utils.get_database_name()
                provider = request.session.get('email')
                r = utils.insert_hotel_service(db_name, id, form.cleaned_data.get('name'), provider)
                if r == 201:
                    return redirect('person:EditService', id = id)
                else:
                    return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Network Error'})
            else:
                return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Invalid Details'})


class EditServiceView(View):
    template_name = 'person/bus_service_edit.html'
    template_name_1 = 'person/hotel_service_edit.html'

    def get_object(self, id):
        return models.ServiceMetaData.objects.filter(id = id)

    def get_user(self, email):
        user = models.UserMetaData.objects.filter(email = email)
        user = user[0]
        db_name = user.db_name
        return utils.get_user(db_name, email)

    def get_form(self, id):
        S = utils.get_bus_service_by_id(id)
        form = forms.EditBusServiceForm(initial = {'id': id, 'service_type': 'Bus', 'name': S.get('name'), 'bus_number': S.get('bus_number'), 'seats': S.get('seats'), 'price': S.get('price'), 'is_ready': S.get('is_ready')})
        return form

    def get_form_1(self, id):
        S = utils.get_hotel_service_by_id(id)
        form = forms.EditHotelServiceForm(initial = {'id': id, 'service_type': 'Hotel', 'name': S.get('name'), 'description': S.get('description'), 'city': S.get('city'), 'address': S.get('address'), 'area': S.get('area'), 'rooms': S.get('rooms'), 'check_in': S.get('check_in'), 'check_out': S.get('check_out'), 'price': S.get('price'), 'is_ready': S.get('is_ready')})
        return form

    def get_service(self, id):
        S = utils.get_bus_service_by_id(id)
        S.update({'combined_list': zip(S.get('route'), S.get('timing'), S.get('boarding_point'))})
        print(S)
        return S

    def get_service_1(self, id):
        S = utils.get_hotel_service_by_id(id)
        return S

    def get(self, request, id):
        if is_authenticated(request) != None:
            service = self.get_object(id)
            if service.count() > 0:
                service = service[0]
                if service.type == 'B':
                    email = request.session.get('email')
                    if email in service.provider:
                        form = self.get_form(id)
                        form1 = forms.ManagersForm()
                        form2 = forms.PasswordForm()
                        form3 = forms.EditRouteForm()
                        return render(request, self.template_name, {'form': form, 'form1': form1, 'form2': form2, 'form3': form3, 'service': self.get_service(id), 'type': get_type(request)})
                    else:
                        print('NOT FOUND')

                elif service.type == 'H':
                    email = request.session.get('email')
                    if email in service.provider:
                        form1 = forms.ManagersForm()
                        form2 = forms.PasswordForm()
                        return render(request, self.template_name_1, {'form': self.get_form_1(id), 'form1': form1, 'form2': form2, 'service': self.get_service_1(id), 'type': get_type(request)})

            else:
                print('NOT FOUND')
        else:
            return redirect('person:Dashboard')

    def post(self, request, id):
        service = self.get_object(id)
        service = service[0]
        if service.type == 'B':
            if 'delete_service' in request.POST:
                user = self.get_user(request.session.get('email'))
                if check_password(request.POST.get('password'), user.get('password')):
                    r = utils.delete_bus_service(id = id)
                    if r == 200:
                        return redirect('person:Services')
                    else:
                        return render(request, self.template_name, {'form': self.get_form(id), 'form1': forms.ManagersForm(), 'form2': forms.PasswordForm(), 'form3': forms.EditRouteForm(), 'error2': '1', 'msg2': 'Network Error', 'service': self.get_service(id), 'type': get_type(request)})
                else:
                    return render(request, self.template_name, {'form': self.get_form(id), 'form1': forms.ManagersForm(), 'form2': forms.PasswordForm(), 'form3': forms.EditRouteForm(), 'error2': '1', 'msg2': 'Incorrect Password', 'service': self.get_service(id), 'type': get_type(request)})
            elif 'add_manager' in request.POST:
                form1 = forms.ManagersForm(request.POST)
                if form1.is_valid():
                    email = form1.cleaned_data.get('email')
                    if email not in service.provider:
                        r = utils.update_bus_service(id = id, provider = email, provider_code = 'ADD')
                        if r == 200:
                            service.provider.append(email)
                            service.save()
                        else:

server/person/templates/person/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title_block %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  </head>
  <body>
      <!-- NAVBAR -->
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
          <div class="container">
              <div class="navbar-brand">
                  <a class="navbar-item" href="https://bulma.io">
                      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
                  </a>
                  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                  </a>
              </div>
              <div id="navbarBasicExample" class="navbar-menu">
                  <div class="navbar-start">
                      <a class="navbar-item" href="{% url 'person:Dashboard' %}">
                          <p style="margin: 10px; font-size: 18px;">Dashboard</p>
                      </a>
                      <a class="navbar-item">
                          <p style="margin: 10px; font-size: 18px;">Hotels</p>
                      </a>
                      <a class="navbar-item">
                          <p style="margin: 10px; font-size: 18px;">Buses</p>
                      </a>
                  </div>
                  <div class="navbar-end">
                      <a class="navbar-item" href="{% url 'person:Admin' %}" {% block admin_block %}{% endblock %}>
                          <p style="margin: 10px; font-size: 18px;">Admin</p>
                      </a>
                      <a class="navbar-item" href="{% url 'person:Services' %}" {% block service_block %}{% endblock %}>
                          <p style="margin: 10px; font-size: 18px;">Services</p>
                      </a>
                      <a class="navbar-item">
                          <p style="margin: 10px; font-size: 18px;">Account</p>
                      </a>
                      <a class="navbar-item" href="{% url 'person:Logout' %}">
                          <p style="margin: 10px; font-size: 18px;">Logout</p>
                      </a>
                  </div>
              </div>
          </div>
     </nav>
     <!-- NAVBAR END -->
     <section class="section">
         <div class="container">
             {% block content_block %}{% endblock %}
         </div>
     </section>
  </body>
</html>

server/person/templates/person/bus_service_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Services{% endblock %}

{% block content_block %}

    <div class="columns has-text-centered">
        <div class="column">
            <div class="box">
                <h3 class="subtitle is-5">Managers</h3>
                {% if service.provider|length == 1 %}
                    {% for provider in service.provider %}
                        <a href="#" class="button is-small is-light">{{ provider }}</a>
                    {% endfor %}
                {% else %}
                    {% for provider in service.provider %}
                    <div>
                            <a href="#" class="button is-small is-light">{{ provider }}</a>
                            <a href="{% url 'person:DeleteManager' id=service.id email=forloop.counter0 %}" class="delete is-small"></a>
                    </div>
                    {% endfor %}
                {% endif %}
                <form class="section" method = "POST">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                            {% render_field form1.email type="text" class="input" placeholder="Email" %}
                        </div>
                    </div>
                    <button name="add_manager" class="button is-fullwidth is-info">Add</button>
                </form>

                <!-- MESSAGES -->

                <div class="tag is-medium">
                    {% if error1 %}
                        <div>
                            {% for field in form1 %}
                                {% if field.errors %}
                                    <div class="content">
                                        <label style="color: red;">{{ field.errors | striptags }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% if msg1 %}
                            <div class="content">
                                <p style="color: red;">{{ msg1 }}</p>
                            </div>
                            {% endif %}
                        </div>
                    {% else %}
                        <div>
                            <div class="content">
                                <p style="color: blue;">Add/Remove Managers</p>
                            </div>
                        </div>
                    {% endif %}
                </div>

                <!-- END MESSAGES -->

            </div>
        </div>
        <div class="column is-6">
            <div class="box">
                <h3 class="subtitle is-5">Manage Service</h3>
                <form class="section has-text-left" method = "POST">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Service ID</label>
                        <div class="control">
                            {% render_field form.id type="text" class="input is-rounded" placeholder="Service ID" %}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Service Name</label>
                        <div class="control">
                            {% render_field form.name type="text" class="input is-rounded" placeholder="Service Name" %}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Service Type</label>
                        <div class="control">
                            {% render_field form.service_type type="text" class="input is-rounded" placeholder="Service Type" %}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Bus Number</label>
                        <div class="control">
                            {% render_field form.bus_number type="text" class="input is-rounded" placeholder="Bus Number" %}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Number Of Seats</label>
                        <div class="control">
                            {% render_field form.seats type="number" class="input is-rounded" placeholder="Number of Seats" %}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Ticket Price</label>
                        <div class="control">
                            {% render_field form.price type="number" class="input is-rounded" placeholder="Ticket Price" %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <label class="checkbox">
                            {% render_field form.is_ready type="checkbox" %} READY
                            </label>
                        </div>
                    </div>
                    <button name="edit_service" class="button is-fullwidth is-info">Update</button>
                </form>

                <!-- MESSAGES -->

                <div class="tag is-medium">
                    {% if error %}
                        {% if error == '1' %}
                        <div>
                            <div class="content">
                                <p style="color: red;">{{ msg }}</p>
                            </div>
                        </div>
                        {% endif %}
                    {% elif success %}
                        {% if success == '1' %}
                        <div>
                            <div class="content">
                                <p style="color: green;">{{ msg }}</p>
                            </div>
                        </div>
                        {% endif %}
                    {% else %}
                        <div>
                            <div class="content">
                                <p style="color: blue;">Check READY after filling all details</p>
                            </div>
                        </div>
                    {% endif %}
                </div>

                <!-- END MESSAGES -->
                <div class="section">
                    <h3 class="subtitle is-5">Edit Route</h3>
                    <div>
                        <table class="table is-fullwidth has-text-centered">
                            <thead>
                                <tr>
                                  <th><abbr title="Number">Sr. No.</abbr></th>
                                  <th>Name</th>
                                  <th>Timing (D : H : M)</th>
                                  <th>Boarding Point</th>
                                  <th>Action</th>
                                </tr>
                          </thead>
                          <tbody>
                              {% for item in service.combined_list %}
                                <tr>
                                    <td>{{ forloop.counter0 }}</td>
                                    <td>{{ item.0 }}</td>
                                    <td>{{ item.1 }}</td>
                                    <td>{{ item.2 }}</td>
                                    <td><a href="{% url 'person:DeleteBusRoute' id=service.id index=forloop.counter0 %}" class="delete"></a></td>
                                <tr>
                              {% endfor %}
                          </tbody>
                        </table>
                    </div>
                    <form class="section has-text-left" method = "POST">
                        {% csrf_token %}
                            <div class="field">
                                <label class="label">Stop Name</label>
                                <div class="control">
                                    {% render_field form3.stop_name type="text" class="input is-rounded" placeholder="Stop Name" %}
                                </div>
                            </div>
                            <div class="field">
                                <label class="label">Boarding Point</label>
                                <div class="control">
                                    {% render_field form3.boarding_point type="text" class="input is-rounded" placeholder="Boardng Point" %}
                                </div>
                            </div>
                            <label class="label">Timing in 24 Hour Format (Day : Hour : Minutes)</label>
                            <div class="field is-horizontal">
                                <div class="field-body columns">
                                    <div class="field column">
                                        <div class="control">
                                            {% render_field form3.day type="number" class="input is-rounded" placeholder="Day Number" %}
                                        </div>
                                    </div>
                                    <div class="field column">
                                        <div class="control">
                                            {% render_field form3.time_hour type="number" class="input is-rounded" placeholder="HH" %}
                                        </div>
                                    </div>
                                    <div class="field column">
                                        <div class="control">
                                            {% render_field form3.time_mins type="number" class="input is-rounded" placeholder="MM" %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                                <button name="edit_route" class="button is-fullwidth is-info">Add</button>

                    </form>

                    <!-- MESSAGES -->

                    <div class="tag is-medium">
                        {% if error3 %}
                            {% if error3 == '1' %}
                            <div>
                                <div class="content">
                                    <p style="color: red;">{{ msg3 }}</p>
                                </div>
                            </div>
                            {% endif %}
                        {% elif success3 %}
                            {% if success3 == '1' %}
                            <div>
                                <div class="content">
                                    <p style="color: green;">{{ msg3 }}</p>
                                </div>
                            </div>
                            {% endif %}
                        {% else %}
                            <div>
                                <div class="content">
                                    <p style="color: blue;">Modify Bus Route</p>
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <!-- END MESSAGES -->

                </div>
            </div>
        </div>
        <div class="column">
            <div class="box">
                <h3 class="subtitle is-5">Delete Service</h3>
                <form class="section" method = "POST">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                            {% render_field form2.password type="password" class="input" placeholder="Your Password" %}
                        </div>
                    </div>
                    <button name="delete_service" class="button is-fullwidth is-info">Delete</button>
                </form>

                <!-- MESSAGES -->

                <div class="tag is-medium">
                    {% if error2 %}
                        <div>
                            <div class="content">
                                <p style="color: red;">{{ msg2 }}</p>
                            </div>
                        </div>
                    {% else %}
                        <div>
                            <div class="content">
                                <p style="color: blue;">Enter Password to Delete Service</p>
                            </div>
                        </div>
                    {% endif %}
                </div>

                <!-- END MESSAGES -->

            </div>
        </div>
    </div>

{% endblock %}